service: sls-meetup-alexa-skill

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    API_KEY: ${env:API_KEY}

plugins:
  - serverless-alexa-skills
  - serverless-dotenv-plugin

custom:
  alexa:
    vendorId: ${env:M2J1OI2ZZB56VP}
    clientId: ${env:amzn1.application-oa2-client.e0a84e4cd8a844ff877dc31206cbfcda}
    clientSecret: ${env:67160e5bf99bd420b9247dbc578ab23f503b29a61632bb54b143a0039556fd85}
    skills:
      - id: amzn1.ask.skill.fc76fc78-f004-41ea-a89c-29d1d234381b
        manifest:
           apis:
            custom:
              endpoint:
                uri: arn:aws:lambda:us-east-1:612821768407:function:sls-meetup-alexa-skill-dev-meetupHandler
           publishingInformation:
            locales:
              en-US:
                name: Project Card
        models:
          en-US:
            interactionModel:
              languageModel:
                invocationName: create issue
                intents:
                  - name: MeetupIntent
                    slots:
                    - name: Name
                      type: AMAZON.SearchQuery
                    samples:
                     - 'name {Name}'
                  - name: AMAZON.HelpIntent
                    samples: []
                  - name: AMAZON.CancelIntent
                    samples: []
                  - name: AMAZON.StopIntent
                    samples: []

functions:
  meetupHandler:
    handler: index.meetupHandler
    events:
      - alexaSkill: amzn1.ask.skill.fc76fc78-f004-41ea-a89c-29d1d234381b


